### ISSUE TITLE
linux 巡检 os-check 当 playbook 有多个任务时 巡检结果 total 显示有问题

### ISSUE THREAD

**Issue by wolf-li** [lework/Ansible-roles#10]
问题：
当巡检 51 台机器时候，巡检报告没有问题，但是当我指定其中一台机器巡检时，发现巡检报告中 总数 （total）与实际不符。
如图所示：
![捕获](https://user-images.githubusercontent.com/59823739/161012762-691ad02e-724a-4efd-98c7-662773767190.PNG)

解决方法：
修改 os-check.py 脚本内容
需要将下面内容
item['summary']['total'] = len(data)
修改为
item['summary']['total'] = item['summary']['ok'] + item['summary']['bad'] + item['summary']['critical'] + item['summary']['error']

**Comment by lework** [comment]
感谢提醒，已修复。
